name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Set up libde265
      run: sudo add-apt-repository -y ppa:strukturag/libde265
    - name: Set up libheif
      run: sudo add-apt-repository -y ppa:strukturag/libheif
    - name: Set up ppa:tonimelisma/ppa
      run: sudo add-apt-repository -y ppa:tonimelisma/ppa
    - name: Install libvips-dev
      run: sudo apt -y install libvips-dev

    - name: Build
      run: go build -v -tags vips -o asciify cmd/main.go

#     - name: Test
#       run: go test -v ./...
