name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.24'

      - name: Install libvips-dev
        run: sudo apt -y install libvips libvips-dev

      - name: Build application
        run: go build -tags vips -o asciify -v cmd/main.go

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: asciify
          path: ./asciify

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.24'

      - name: Install dependencies
        run: go mod tidy

      - name: Install semantic-release
        run: |
          curl -sL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt-get install -y nodejs
          npm install -g semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/github

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: asciify
          path: ./asciify

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release